// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from 'prisma/config'
import { Config } from './src/config/config'
import { logger } from './src/config/Logger'

const databaseUrl = Config.DATABASE_URL

if (databaseUrl === undefined) {
  logger.error('DATABASE_URL is not defined')
  throw new Error('DATABASE_URL is not defined')
}

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations'
  },
  datasource: {
    url: databaseUrl
  }

})
